name: Foo
on:
  repository_dispatch:
    types: [deploy]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Echo
        env:
          TARGET: ${{ github.event.client_payload.target }}
          BRANCH: ${{ github.event.client_payload.branch }}
          COMMIT: ${{ github.event.client_payload.commit }}
        run: |
          echo $TARGET
          echo $BRANCH
          echo $COMMIT
