name: Foo
on:
  repository_dispatch:
    types: [deploy]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    name: 'Deploy to ${{ github.event.client_payload.environment }}'
    environment: '${{github.event.client_payload.environment}}'
    
    env:
      INPUT_ENVIRONMENT: ${{ github.event.client_payload.environment }}
      INPUT_REF: ${{ github.event.client_payload.ref }}
      
    if: ${{ env.INPUT_ENVIRONMENT == 'production' || env.INPUT_ENVIRONMENT == 'staging' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: private
      
      - name: Checkout public repo
        uses: actions/checkout@v3
        with:
          repository: kamilkisiela/bar
          path: public
          ref: ${{ github.event.client_payload.ref }}
          
      - name: Move
        run: cp ./private/deployment/* ./public/deployment
        
      - name: Set variables for staging environment
        if: github.event.client_payload.environment == 'staging'
        run: |
          echo "stack_name=theguild/hive/staging" >> $GITHUB_ENV

      - name: Set variables for production environment
        if: github.event.client_payload.environment == 'production'
        run: |
          echo "stack_name=theguild/hive/prod" >> $GITHUB_ENV
      
      - name: Echo
        working-directory: public/deployment
        env:
          STACK_NAME: ${{ env.stack_name }}
        run: |
          ls
          git rev-parse HEAD
          echo $STACK_NAME
          
          
          
