name: Foo
on:
  repository_dispatch:
    types: [deploy]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    name: 'Deploy to ${{ github.event.client_payload.environment }}'
    environment: '${{github.event.client_payload.environment}}'


    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: private
      
      - name: Checkout public repo
        uses: actions/checkout@v3
        with:
          repository: kamilkisiela/bar
          path: public
          ref: ${{ github.event.client_payload.ref }}
          
      - name: Move
        run: cp ./private/deployment/* ./public/deployment
      
      - name: Echo
        working-directory: public/deployment
        run: |
          ls
          git rev-parse HEAD
          
          
          
