name: Foo
on:
  repository_dispatch:
    types: [deploy]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Checkout public repo
        uses: actions/checkout@v3
        with:
          repository: kamilkisiela/bar
          path: bar
          ref: ${{ github.event.client_payload.commit }}
          
      - name: Move
        run: cp ./deployment/* ./bar/deployment
      
      - name: Echo
        working-directory: bar/deployment
        run: ls
          
          
          
